services:
  warehouse:
    image: postgres:16
    environment:
      - POSTGRES_USER=warehouse
      - POSTGRES_PASSWORD=warehouse
      - POSTGRES_DB=warehouse
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "warehouse"]
      interval: 10s
      retries: 5
      start_period: 5s
    volumes:
      - ~/.docker-volumes/turn-one/workflows/warehouse:/var/lib/postgresql/data
    restart: always
  spark-master:
    build:
      dockerfile: ./images/spark/Dockerfile
    container_name: spark-master
    ports:
      - "38080:8080"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    command: >
      bash -c "/opt/spark/sbin/start-master.sh && tail -f /dev/null"

  spark-worker:
    build:
      dockerfile: ./images/spark/Dockerfile
    scale: 3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    command: >
      bash -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000" # MinIO server
      - "9001:9001" # MinIO console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - ~/.docker-volumes/turn-one/workflows/minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5

